import type { AppLanguage } from './languageOptions';

interface RepositoryHistoryTranslations {
  repositoryHistory: string;
  repositoryHistoryTooltip: string;
  loadingRepositoryHistory: string;
  noRepositoryHistory: string;
  repositoryHistoryUnavailable: string;
  commitFiles: string;
  loadingRevisionFiles: string;
  noRevisionFiles: string;
  revisionFilesUnavailable: string;
  backToHead: string;
  browseCommit: string;
  openSnapshotFile: string;
  snapshotReadOnly: string;
  snapshotFileUnavailable: string;
  head: string;
}

export interface HistoryTranslations extends RepositoryHistoryTranslations {
  history: string; historyTooltip: string; documentHistory: string; closeHistory: string; loadHistory: string; loadingHistory: string;
  retry: string; noHistory: string; compareSelected: string; noCommitMessage: string; viewRevision: string; compareCurrent: string;
  unsupportedRuntime: string; gitUnavailable: string; notRepository: string; historyUnavailable: string; returnCurrent: string;
  sourceDiff: string; renderedDiff: string; diffMode: string; added: string; removed: string; unchanged: string;
  status: string; left: string; right: string; source: string; revision: string; diff: string; current: string; workingCopy: string;
}

const REPOSITORY_HISTORY_TRANSLATIONS: Record<AppLanguage, RepositoryHistoryTranslations> = {
  en: { repositoryHistory: 'Repository history', repositoryHistoryTooltip: 'Browse repository commits and read-only snapshots', loadingRepositoryHistory: 'Loading repository history…', noRepositoryHistory: 'No repository commits found.', repositoryHistoryUnavailable: 'Repository history is unavailable.', commitFiles: 'Files in this commit', loadingRevisionFiles: 'Loading revision files…', noRevisionFiles: 'No files are available in this revision.', revisionFilesUnavailable: 'Revision files are unavailable.', backToHead: 'Back to current HEAD', browseCommit: 'Browse commit', openSnapshotFile: 'Open read-only snapshot', snapshotReadOnly: 'Read-only Git snapshot', snapshotFileUnavailable: 'This snapshot file is unavailable.', head: 'HEAD' },
  vi: { repositoryHistory: 'Lịch sử kho mã', repositoryHistoryTooltip: 'Duyệt commit và ảnh chụp chỉ đọc của kho mã', loadingRepositoryHistory: 'Đang tải lịch sử kho mã…', noRepositoryHistory: 'Không tìm thấy commit trong kho mã.', repositoryHistoryUnavailable: 'Lịch sử kho mã không khả dụng.', commitFiles: 'Tệp trong commit này', loadingRevisionFiles: 'Đang tải tệp của phiên bản…', noRevisionFiles: 'Không có tệp trong phiên bản này.', revisionFilesUnavailable: 'Danh sách tệp phiên bản không khả dụng.', backToHead: 'Quay lại HEAD hiện tại', browseCommit: 'Duyệt commit', openSnapshotFile: 'Mở ảnh chụp chỉ đọc', snapshotReadOnly: 'Ảnh chụp Git chỉ đọc', snapshotFileUnavailable: 'Tệp ảnh chụp này không khả dụng.', head: 'HEAD' },
  fr: { repositoryHistory: 'Historique du dépôt', repositoryHistoryTooltip: 'Parcourir les commits et instantanés en lecture seule', loadingRepositoryHistory: 'Chargement de l’historique du dépôt…', noRepositoryHistory: 'Aucun commit trouvé dans le dépôt.', repositoryHistoryUnavailable: 'L’historique du dépôt est indisponible.', commitFiles: 'Fichiers de ce commit', loadingRevisionFiles: 'Chargement des fichiers de la révision…', noRevisionFiles: 'Aucun fichier disponible dans cette révision.', revisionFilesUnavailable: 'Les fichiers de la révision sont indisponibles.', backToHead: 'Retour au HEAD actuel', browseCommit: 'Parcourir le commit', openSnapshotFile: 'Ouvrir l’instantané en lecture seule', snapshotReadOnly: 'Instantané Git en lecture seule', snapshotFileUnavailable: 'Ce fichier d’instantané est indisponible.', head: 'HEAD' },
  es: { repositoryHistory: 'Historial del repositorio', repositoryHistoryTooltip: 'Explorar commits e instantáneas de solo lectura', loadingRepositoryHistory: 'Cargando historial del repositorio…', noRepositoryHistory: 'No se encontraron commits en el repositorio.', repositoryHistoryUnavailable: 'El historial del repositorio no está disponible.', commitFiles: 'Archivos de este commit', loadingRevisionFiles: 'Cargando archivos de la revisión…', noRevisionFiles: 'No hay archivos disponibles en esta revisión.', revisionFilesUnavailable: 'Los archivos de la revisión no están disponibles.', backToHead: 'Volver al HEAD actual', browseCommit: 'Explorar commit', openSnapshotFile: 'Abrir instantánea de solo lectura', snapshotReadOnly: 'Instantánea Git de solo lectura', snapshotFileUnavailable: 'Este archivo de instantánea no está disponible.', head: 'HEAD' },
  zh: { repositoryHistory: '仓库历史', repositoryHistoryTooltip: '浏览仓库提交和只读快照', loadingRepositoryHistory: '正在加载仓库历史…', noRepositoryHistory: '未找到仓库提交。', repositoryHistoryUnavailable: '仓库历史不可用。', commitFiles: '此提交中的文件', loadingRevisionFiles: '正在加载版本文件…', noRevisionFiles: '此版本中没有可用文件。', revisionFilesUnavailable: '版本文件不可用。', backToHead: '返回当前 HEAD', browseCommit: '浏览提交', openSnapshotFile: '打开只读快照', snapshotReadOnly: '只读 Git 快照', snapshotFileUnavailable: '此快照文件不可用。', head: 'HEAD' },
  no: { repositoryHistory: 'Repositoriehistorikk', repositoryHistoryTooltip: 'Bla gjennom commits og skrivebeskyttede øyeblikksbilder', loadingRepositoryHistory: 'Laster repositoriehistorikk…', noRepositoryHistory: 'Ingen commits funnet i repositoriet.', repositoryHistoryUnavailable: 'Repositoriehistorikk er utilgjengelig.', commitFiles: 'Filer i denne commiten', loadingRevisionFiles: 'Laster revisjonsfiler…', noRevisionFiles: 'Ingen filer er tilgjengelige i denne revisjonen.', revisionFilesUnavailable: 'Revisjonsfiler er utilgjengelige.', backToHead: 'Tilbake til gjeldende HEAD', browseCommit: 'Bla gjennom commit', openSnapshotFile: 'Åpne skrivebeskyttet øyeblikksbilde', snapshotReadOnly: 'Skrivebeskyttet Git-øyeblikksbilde', snapshotFileUnavailable: 'Denne øyeblikksbildefilen er utilgjengelig.', head: 'HEAD' },
  ja: { repositoryHistory: 'リポジトリ履歴', repositoryHistoryTooltip: 'コミットと読み取り専用スナップショットを参照', loadingRepositoryHistory: 'リポジトリ履歴を読み込み中…', noRepositoryHistory: 'リポジトリのコミットが見つかりません。', repositoryHistoryUnavailable: 'リポジトリ履歴を利用できません。', commitFiles: 'このコミットのファイル', loadingRevisionFiles: 'リビジョンのファイルを読み込み中…', noRevisionFiles: 'このリビジョンに利用可能なファイルはありません。', revisionFilesUnavailable: 'リビジョンのファイルを利用できません。', backToHead: '現在の HEAD に戻る', browseCommit: 'コミットを参照', openSnapshotFile: '読み取り専用スナップショットを開く', snapshotReadOnly: '読み取り専用 Git スナップショット', snapshotFileUnavailable: 'このスナップショットファイルは利用できません。', head: 'HEAD' },
  ko: { repositoryHistory: '저장소 기록', repositoryHistoryTooltip: '커밋과 읽기 전용 스냅샷 탐색', loadingRepositoryHistory: '저장소 기록 불러오는 중…', noRepositoryHistory: '저장소 커밋을 찾을 수 없습니다.', repositoryHistoryUnavailable: '저장소 기록을 사용할 수 없습니다.', commitFiles: '이 커밋의 파일', loadingRevisionFiles: '리비전 파일 불러오는 중…', noRevisionFiles: '이 리비전에 사용 가능한 파일이 없습니다.', revisionFilesUnavailable: '리비전 파일을 사용할 수 없습니다.', backToHead: '현재 HEAD로 돌아가기', browseCommit: '커밋 탐색', openSnapshotFile: '읽기 전용 스냅샷 열기', snapshotReadOnly: '읽기 전용 Git 스냅샷', snapshotFileUnavailable: '이 스냅샷 파일을 사용할 수 없습니다.', head: 'HEAD' },
  ru: { repositoryHistory: 'История репозитория', repositoryHistoryTooltip: 'Просматривать коммиты и снимки только для чтения', loadingRepositoryHistory: 'Загрузка истории репозитория…', noRepositoryHistory: 'Коммиты репозитория не найдены.', repositoryHistoryUnavailable: 'История репозитория недоступна.', commitFiles: 'Файлы этого коммита', loadingRevisionFiles: 'Загрузка файлов ревизии…', noRevisionFiles: 'В этой ревизии нет доступных файлов.', revisionFilesUnavailable: 'Файлы ревизии недоступны.', backToHead: 'Вернуться к текущему HEAD', browseCommit: 'Просмотреть коммит', openSnapshotFile: 'Открыть снимок только для чтения', snapshotReadOnly: 'Снимок Git только для чтения', snapshotFileUnavailable: 'Этот файл снимка недоступен.', head: 'HEAD' },
};

export const HISTORY_TRANSLATIONS: Record<AppLanguage, HistoryTranslations> = {
  en: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.en,
    history: 'History', historyTooltip: 'Browse document Git history', documentHistory: 'Document history', closeHistory: 'Close history', loadHistory: 'Load history', loadingHistory: 'Loading history…', retry: 'Retry', noHistory: 'No Git history for this document.', compareSelected: 'Compare selected', noCommitMessage: '(no commit message)', viewRevision: 'View revision', compareCurrent: 'Compare with current', unsupportedRuntime: 'Git history is not supported in this runtime.', gitUnavailable: 'Git is unavailable on this system.', notRepository: 'This document is not inside a Git repository.', historyUnavailable: 'Git history is unavailable.', returnCurrent: 'Return to current', sourceDiff: 'Source Diff', renderedDiff: 'Rendered Diff', diffMode: 'Diff mode', added: 'Added', removed: 'Removed', unchanged: 'Unchanged', status: 'Status', left: 'Left', right: 'Right', source: 'Source', revision: 'Revision', diff: 'Diff', current: 'Current', workingCopy: 'Working copy',
  },
  vi: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.vi,
    history: 'Lịch sử', historyTooltip: 'Xem lịch sử Git của tài liệu', documentHistory: 'Lịch sử tài liệu', closeHistory: 'Đóng lịch sử', loadHistory: 'Tải lịch sử', loadingHistory: 'Đang tải lịch sử…', retry: 'Thử lại', noHistory: 'Tài liệu này chưa có lịch sử Git.', compareSelected: 'So sánh mục đã chọn', noCommitMessage: '(không có thông điệp commit)', viewRevision: 'Xem phiên bản', compareCurrent: 'So sánh với hiện tại', unsupportedRuntime: 'Môi trường này không hỗ trợ lịch sử Git.', gitUnavailable: 'Git không khả dụng trên hệ thống này.', notRepository: 'Tài liệu này không nằm trong kho Git.', historyUnavailable: 'Lịch sử Git không khả dụng.', returnCurrent: 'Trở về hiện tại', sourceDiff: 'So sánh mã nguồn', renderedDiff: 'So sánh bản hiển thị', diffMode: 'Chế độ so sánh', added: 'Đã thêm', removed: 'Đã xóa', unchanged: 'Không đổi', status: 'Trạng thái', left: 'Trái', right: 'Phải', source: 'Nguồn', revision: 'Phiên bản', diff: 'So sánh', current: 'Hiện tại', workingCopy: 'Bản đang sửa',
  },
  fr: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.fr,
    history: 'Historique', historyTooltip: 'Parcourir l’historique Git du document', documentHistory: 'Historique du document', closeHistory: 'Fermer l’historique', loadHistory: 'Charger l’historique', loadingHistory: 'Chargement de l’historique…', retry: 'Réessayer', noHistory: 'Aucun historique Git pour ce document.', compareSelected: 'Comparer la sélection', noCommitMessage: '(aucun message de commit)', viewRevision: 'Voir la révision', compareCurrent: 'Comparer à la version actuelle', unsupportedRuntime: 'L’historique Git n’est pas pris en charge dans cet environnement.', gitUnavailable: 'Git est indisponible sur ce système.', notRepository: 'Ce document ne se trouve pas dans un dépôt Git.', historyUnavailable: 'L’historique Git est indisponible.', returnCurrent: 'Revenir à la version actuelle', sourceDiff: 'Diff source', renderedDiff: 'Diff rendu', diffMode: 'Mode de comparaison', added: 'Ajouté', removed: 'Supprimé', unchanged: 'Inchangé', status: 'État', left: 'Gauche', right: 'Droite', source: 'Source', revision: 'Révision', diff: 'Diff', current: 'Actuel', workingCopy: 'Copie de travail',
  },
  es: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.es,
    history: 'Historial', historyTooltip: 'Explorar el historial Git del documento', documentHistory: 'Historial del documento', closeHistory: 'Cerrar historial', loadHistory: 'Cargar historial', loadingHistory: 'Cargando historial…', retry: 'Reintentar', noHistory: 'No hay historial Git para este documento.', compareSelected: 'Comparar seleccionados', noCommitMessage: '(sin mensaje de commit)', viewRevision: 'Ver revisión', compareCurrent: 'Comparar con actual', unsupportedRuntime: 'El historial Git no es compatible con este entorno.', gitUnavailable: 'Git no está disponible en este sistema.', notRepository: 'Este documento no está dentro de un repositorio Git.', historyUnavailable: 'El historial Git no está disponible.', returnCurrent: 'Volver a actual', sourceDiff: 'Diff de código fuente', renderedDiff: 'Diff renderizado', diffMode: 'Modo de comparación', added: 'Añadido', removed: 'Eliminado', unchanged: 'Sin cambios', status: 'Estado', left: 'Izquierda', right: 'Derecha', source: 'Fuente', revision: 'Revisión', diff: 'Diff', current: 'Actual', workingCopy: 'Copia de trabajo',
  },
  zh: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.zh,
    history: '历史记录', historyTooltip: '浏览文档 Git 历史', documentHistory: '文档历史', closeHistory: '关闭历史', loadHistory: '加载历史', loadingHistory: '正在加载历史…', retry: '重试', noHistory: '此文档没有 Git 历史记录。', compareSelected: '比较所选版本', noCommitMessage: '（无提交信息）', viewRevision: '查看版本', compareCurrent: '与当前版本比较', unsupportedRuntime: '此运行环境不支持 Git 历史。', gitUnavailable: '此系统上 Git 不可用。', notRepository: '此文档不在 Git 仓库中。', historyUnavailable: 'Git 历史不可用。', returnCurrent: '返回当前版本', sourceDiff: '源码差异', renderedDiff: '渲染差异', diffMode: '差异模式', added: '已添加', removed: '已删除', unchanged: '未更改', status: '状态', left: '左侧', right: '右侧', source: '源码', revision: '版本', diff: '差异', current: '当前', workingCopy: '工作副本',
  },
  no: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.no,
    history: 'Historikk', historyTooltip: 'Se dokumentets Git-historikk', documentHistory: 'Dokumenthistorikk', closeHistory: 'Lukk historikk', loadHistory: 'Last historikk', loadingHistory: 'Laster historikk…', retry: 'Prøv igjen', noHistory: 'Ingen Git-historikk for dette dokumentet.', compareSelected: 'Sammenlign valgte', noCommitMessage: '(ingen commit-melding)', viewRevision: 'Vis revisjon', compareCurrent: 'Sammenlign med gjeldende', unsupportedRuntime: 'Git-historikk støttes ikke i dette kjøremiljøet.', gitUnavailable: 'Git er ikke tilgjengelig på dette systemet.', notRepository: 'Dokumentet ligger ikke i et Git-repositorium.', historyUnavailable: 'Git-historikk er utilgjengelig.', returnCurrent: 'Tilbake til gjeldende', sourceDiff: 'Kildediff', renderedDiff: 'Rendret diff', diffMode: 'Diffmodus', added: 'Lagt til', removed: 'Fjernet', unchanged: 'Uendret', status: 'Status', left: 'Venstre', right: 'Høyre', source: 'Kilde', revision: 'Revisjon', diff: 'Diff', current: 'Gjeldende', workingCopy: 'Arbeidskopi',
  },
  ja: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.ja,
    history: '履歴', historyTooltip: '文書の Git 履歴を表示', documentHistory: '文書履歴', closeHistory: '履歴を閉じる', loadHistory: '履歴を読み込む', loadingHistory: '履歴を読み込み中…', retry: '再試行', noHistory: 'この文書には Git 履歴がありません。', compareSelected: '選択した版を比較', noCommitMessage: '（コミットメッセージなし）', viewRevision: 'リビジョンを表示', compareCurrent: '現在と比較', unsupportedRuntime: 'この実行環境では Git 履歴はサポートされていません。', gitUnavailable: 'このシステムでは Git を利用できません。', notRepository: 'この文書は Git リポジトリ内にありません。', historyUnavailable: 'Git 履歴を利用できません。', returnCurrent: '現在に戻る', sourceDiff: 'ソース差分', renderedDiff: 'レンダリング差分', diffMode: '差分モード', added: '追加', removed: '削除', unchanged: '変更なし', status: '状態', left: '左', right: '右', source: 'ソース', revision: 'リビジョン', diff: '差分', current: '現在', workingCopy: '作業コピー',
  },
  ko: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.ko,
    history: '기록', historyTooltip: '문서 Git 기록 보기', documentHistory: '문서 기록', closeHistory: '기록 닫기', loadHistory: '기록 불러오기', loadingHistory: '기록 불러오는 중…', retry: '다시 시도', noHistory: '이 문서에는 Git 기록이 없습니다.', compareSelected: '선택한 항목 비교', noCommitMessage: '(커밋 메시지 없음)', viewRevision: '리비전 보기', compareCurrent: '현재 버전과 비교', unsupportedRuntime: '이 런타임에서는 Git 기록을 지원하지 않습니다.', gitUnavailable: '이 시스템에서 Git을 사용할 수 없습니다.', notRepository: '이 문서는 Git 저장소 안에 있지 않습니다.', historyUnavailable: 'Git 기록을 사용할 수 없습니다.', returnCurrent: '현재 버전으로 돌아가기', sourceDiff: '소스 Diff', renderedDiff: '렌더링 Diff', diffMode: 'Diff 모드', added: '추가됨', removed: '삭제됨', unchanged: '변경 없음', status: '상태', left: '왼쪽', right: '오른쪽', source: '소스', revision: '리비전', diff: 'Diff', current: '현재', workingCopy: '작업 사본',
  },
  ru: {
    ...REPOSITORY_HISTORY_TRANSLATIONS.ru,
    history: 'История', historyTooltip: 'Просмотреть Git-историю документа', documentHistory: 'История документа', closeHistory: 'Закрыть историю', loadHistory: 'Загрузить историю', loadingHistory: 'Загрузка истории…', retry: 'Повторить', noHistory: 'Для этого документа нет Git-истории.', compareSelected: 'Сравнить выбранные', noCommitMessage: '(нет сообщения коммита)', viewRevision: 'Открыть ревизию', compareCurrent: 'Сравнить с текущей', unsupportedRuntime: 'Git-история не поддерживается в этой среде.', gitUnavailable: 'Git недоступен в этой системе.', notRepository: 'Документ не находится в Git-репозитории.', historyUnavailable: 'Git-история недоступна.', returnCurrent: 'Вернуться к текущей', sourceDiff: 'Исходный diff', renderedDiff: 'Отрисованный diff', diffMode: 'Режим сравнения', added: 'Добавлено', removed: 'Удалено', unchanged: 'Без изменений', status: 'Статус', left: 'Слева', right: 'Справа', source: 'Исходник', revision: 'Ревизия', diff: 'Diff', current: 'Текущая', workingCopy: 'Рабочая копия',
  },
};

export function getHistoryTranslations(language?: string): HistoryTranslations {
  return HISTORY_TRANSLATIONS[language as AppLanguage] ?? HISTORY_TRANSLATIONS.en;
}
