import { useMemo } from 'react';
import type { InsightsTranslations } from '../../contexts/insightsTranslations';
import { ensureInsightsUiTranslations, type InsightsUiTranslations } from '../../contexts/insightsUiTranslations';
import type { AnalyzedDocument } from '../../insights/analyzeDocument';
import type { InsightsRelationshipWeights } from '../../insights/config';
import { buildRelationshipCandidates, RELATIONSHIP_PRESETS, scoreRelatedDocument, type RelationshipDocument, type RelatedDocumentScore } from '../../insights/relationships';

export interface RelatedViewProps { readonly documents: readonly AnalyzedDocument[]; readonly labels?: InsightsTranslations | InsightsUiTranslations; readonly selectedPath?: string; readonly preset?: keyof typeof RELATIONSHIP_PRESETS; readonly weights?: Partial<InsightsRelationshipWeights>; readonly onSelectPath?: (path: string) => void; }
function relationshipDocument(document: AnalyzedDocument): RelationshipDocument { return { path: document.path, title: document.title, tags: document.tags, headings: document.headings.map(heading => heading.text), links: document.references.filter(reference => !reference.remote && reference.kind !== 'media' && reference.kind !== 'html-media').map(reference => reference.target), terms: document.terminology, terminologySignatures: document.terminologySignatures }; }
function pairKey(a: string, b: string): string { return [a, b].sort().join('\u0000'); }
function evidenceLines(score: RelatedDocumentScore, labels: InsightsUiTranslations): string[] { const evidence = score.evidence; const lines: string[] = []; if (evidence.directLinks.length) lines.push(`${labels.directLinks}: ${evidence.directLinks.join(', ')}`); if (evidence.sharedTags.length) lines.push(`${labels.sharedTags}: ${evidence.sharedTags.join(', ')}`); if (evidence.sharedHeadings.length) lines.push(`${labels.sharedHeadings}: ${evidence.sharedHeadings.join(', ')}`); if (evidence.sharedTitleTerms.length) lines.push(`${labels.sharedTitleTerms}: ${evidence.sharedTitleTerms.join(', ')}`); if (evidence.sharedTerms.length) lines.push(`${labels.sharedTerminology}: ${evidence.sharedTerms.slice(0, 8).join(', ')}`); return lines; }
function format(value: string, replacements: Readonly<Record<string, string | number>>): string { return Object.entries(replacements).reduce((result, [key, replacement]) => result.replace(`{${key}}`, String(replacement)), value); }

export function RelatedView({ documents, labels: suppliedLabels, selectedPath, preset = 'default', weights, onSelectPath }: RelatedViewProps) {
  const labels = ensureInsightsUiTranslations(suppliedLabels);
  const ranked = useMemo(() => { const relationshipDocuments = documents.map(relationshipDocument); const byPath = new Map(relationshipDocuments.map(document => [document.path, document])); const source = (selectedPath ? byPath.get(selectedPath) : undefined) ?? relationshipDocuments[0]; if (!source) return { source: undefined, scores: [] as RelatedDocumentScore[] }; const candidates = buildRelationshipCandidates(relationshipDocuments); const selectedWeights = weights ?? RELATIONSHIP_PRESETS[preset]; const scores = relationshipDocuments.filter(document => document.path !== source.path && candidates.has(pairKey(source.path, document.path))).map(document => scoreRelatedDocument(source, document, selectedWeights)).filter(result => result.score > 0).sort((a, b) => b.score - a.score || a.targetPath.localeCompare(b.targetPath)); return { source, scores }; }, [documents, preset, selectedPath, weights]);
  const titles = useMemo(() => new Map(documents.map(document => [document.path, document.title])), [documents]);
  if (!ranked.source) return <div className="workspace-insights__empty">{labels.noRelatedDocuments}</div>;
  const presetLabel = labels.presentation.relationshipPresets[preset];
  return <div className="insights-related"><div className="insights-view-summary">{format(labels.relatedTo, { title: ranked.source.title })} · {format(labels.ranking, { preset: presetLabel })}</div>{!ranked.scores.length && <div className="workspace-insights__empty">{labels.noRelatedDocuments}</div>}<ol className="insights-list insights-related__list">{ranked.scores.map(result => { const evidence = evidenceLines(result, labels); const title = titles.get(result.targetPath) ?? result.targetPath; return <li key={result.targetPath} className="insights-list__row insights-related__row"><div className="insights-related__details"><button type="button" className="insights-related__document" onClick={() => onSelectPath?.(result.targetPath)}>{title}</button><span>{format(labels.score, { score: Math.round(result.score) })}</span>{evidence.map(line => <span key={line}>{line}</span>)}</div></li>; })}</ol></div>;
}
