// =============================================================================
// App.tsx — Root component
// =============================================================================

import { useState, useCallback, useRef } from 'react';
import { useAppState } from './contexts/AppStateContext';
import { WorkspaceSelection } from './components/Workspace/WorkspaceSelection';
import { Topbar } from './components/Topbar/Topbar';
import { Sidebar } from './components/Sidebar/Sidebar';
import { Content } from './components/Content/Content';
import { TableOfContents } from './components/TOC/TableOfContents';
import { SearchOverlay } from './components/Search/SearchOverlay';
import { MediaModal } from './components/Modal/MediaModal';
import { SettingsModal } from './components/Settings/SettingsModal';
import { Button } from './components/shared/Button';
import { ChevronUpIcon } from './components/shared/icons';
import { useKeyboard } from './hooks/useKeyboard';
import { useResize } from './hooks/useResize';
import { useScrollVisibility } from './hooks/useScrollVisibility';

export function App() {
  const { state } = useAppState();
  const [searchOpen, setSearchOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalTarget, setModalTarget] = useState<HTMLElement | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  const { isVisible: scrollTopVisible, scrollToTop } = useScrollVisibility(scrollRef);

  // Sidebar resize handle
  useResize('sidebarResize', 'sidebar');

  // Expand / Collapse all sections
  const expandAll = useCallback(() => {
    document.querySelectorAll('.mdn-section').forEach((s) => {
      (s as HTMLElement).dataset.expanded = 'true';
    });
  }, []);

  const collapseAll = useCallback(() => {
    document.querySelectorAll('.mdn-section').forEach((s) => {
      (s as HTMLElement).dataset.expanded = 'false';
    });
  }, []);

  // Keyboard shortcuts
  useKeyboard({
    onSearchOpen: () => setSearchOpen(true),
    onSearchClose: () => setSearchOpen(false),
    onSettingsOpen: () => setSettingsOpen(true),
    onSettingsClose: () => setSettingsOpen(false),
    onExpandAll: expandAll,
    onCollapseAll: collapseAll,
    isSearchOpen: searchOpen,
    isSettingsOpen: settingsOpen,
    isModalOpen: modalOpen,
  });

  // Expose global functions for inline handlers generated by HtmlRenderer
  // (section toggles, table sort/filter, copy code, etc.)
  useGlobalHandlers();

  // Image click → open media modal
  const onImageClick = useCallback((el: HTMLElement) => {
    setModalTarget(el);
    setModalOpen(true);
  }, []);

  if (state.isLoading && !state.workspaceName) {
    return (
      <div className="state-screen" style={{ display: 'flex', height: '100vh', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'var(--bg)', color: 'var(--tx)' }}>
        <div className="spinner" />
        <div className="state-screen__title" style={{ marginTop: '12px', fontSize: '14px', fontWeight: 500 }}>Loading docs…</div>
      </div>
    );
  }

  if (!state.workspaceName) {
    return <WorkspaceSelection />;
  }

  return (
    <div className="app">
      <Topbar
        onSearchOpen={() => setSearchOpen(true)}
        onSettingsOpen={() => setSettingsOpen(true)}
        onExpandAll={expandAll}
        onCollapseAll={collapseAll}
      />
      <div className="body">
        <Sidebar />
        <div className="sidebar-resize" id="sidebarResize" role="separator" aria-label="Resize sidebar" />
        <div style={{ position: 'relative', display: 'flex', flex: 1, overflow: 'hidden' }}>
          <Content onImageClick={onImageClick} scrollRef={scrollRef} />
          {/* Scroll to top button */}
          <Button
            className={`scroll-to-top-btn${scrollTopVisible ? ' is-visible' : ''}`}
            onClick={scrollToTop}
            tooltip="Scroll to Top"
            tooltipPos="above"
            icon={<ChevronUpIcon />}
          />
        </div>
        <TableOfContents />
      </div>

      {/* Overlays */}
      <SearchOverlay isOpen={searchOpen} onClose={() => setSearchOpen(false)} />
      <MediaModal isOpen={modalOpen} onClose={() => setModalOpen(false)} clickedElement={modalTarget} />
      <SettingsModal isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} />
    </div>
  );
}

// ── Global handlers for inline event attributes from HtmlRenderer ───────────
// The host-side HtmlRenderer produces HTML with inline onclick attributes
// (e.g., onclick="UI.toggleSection(this)"). These globals bridge that HTML
// into the React app. This is a pragmatic migration step — eventually
// the renderer should produce handler-free HTML.
function useGlobalHandlers() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const win = window as any;

  // UI.toggleSection
  if (!win.UI) win.UI = {};
  win.UI.toggleSection = (headerEl: HTMLElement) => {
    const section = headerEl.closest('.mdn-section') as HTMLElement | null;
    if (!section) return;
    const expanded = section.dataset.expanded === 'true';
    section.dataset.expanded = expanded ? 'false' : 'true';
    headerEl.setAttribute('aria-expanded', String(!expanded));
  };
  win.UI.expandAll = () => {
    document.querySelectorAll('.mdn-section').forEach((s) => {
      (s as HTMLElement).dataset.expanded = 'true';
    });
  };
  win.UI.collapseAll = () => {
    document.querySelectorAll('.mdn-section').forEach((s) => {
      (s as HTMLElement).dataset.expanded = 'false';
    });
  };
  win.UI.setHtmlMode = (wrap: HTMLElement, mode: string) => {
    wrap.dataset.mode = mode;
    const langLabel = wrap.querySelector('.mdn-codeblock-lang') as HTMLElement | null;
    const previewBody = wrap.querySelector('.mdn-html-preview-body') as HTMLElement | null;
    const codeBody = wrap.querySelector('.mdn-codeblock-body') as HTMLElement | null;
    if (mode === 'preview') {
      if (langLabel) langLabel.textContent = 'HTML Preview';
      if (previewBody) previewBody.style.display = '';
      if (codeBody) codeBody.style.display = 'none';
    } else {
      if (langLabel) langLabel.textContent = 'HTML';
      if (previewBody) previewBody.style.display = 'none';
      if (codeBody) codeBody.style.display = 'flex';
    }
  };
  win.UI.toggleHtmlMode = (btn: HTMLElement) => {
    const wrap = btn.closest('.mdn-codeblock') as HTMLElement | null;
    if (!wrap) return;
    const currentMode = wrap.dataset.mode || 'preview';
    win.UI.setHtmlMode(wrap, currentMode === 'preview' ? 'code' : 'preview');
  };
  win.UI.refresh = () => {
    // Handled by React bridge, but provide a fallback
  };

  // UI_copyCode (global function referenced by rendered HTML)
  win.UI_copyCode = (btn: HTMLElement) => {
    const code = btn.closest('.mdn-codeblock')?.querySelector('code')?.innerText ?? '';
    // Use platform bridge for clipboard (injected separately if needed)
    try {
      navigator.clipboard.writeText(code);
    } catch {
      // Fallback: post message if available
    }
    btn.classList.add('is-copied');
    const tooltip = btn.querySelector('.tooltip-text');
    if (tooltip) tooltip.textContent = 'Copied!';
    setTimeout(() => {
      btn.classList.remove('is-copied');
      if (tooltip) tooltip.textContent = 'Copy code';
    }, 2000);
  };

  // Table object (for inline onclick handlers)
  if (!win.Table) win.Table = {};
  // Table object (for inline onclick handlers)
  if (!win.Table) win.Table = {};
  win.Table.states = win.Table.states || {};

  win.Table.initState = (tableId: string) => {
    if (!win.Table.states[tableId]) {
      win.Table.states[tableId] = {
        expanded: false,
        searchQuery: '',
        filters: {},
        chartInstance: null,
        currentView: 'table',
        chartable: false,
        labelColIdx: 0,
        dataColIdxs: []
      };
    }
    return win.Table.states[tableId];
  };

  win.Table.sort = (tableId: string, colIndex: number) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const tbody = table.querySelector('tbody');
    if (!tbody) return;
    const rows = [...tbody.querySelectorAll('tr')];
    const th = table.querySelectorAll('.mdn-th')[colIndex] as HTMLElement | null;
    if (!th) return;
    const asc = !th.classList.contains('sort-asc');
    table.querySelectorAll('.mdn-th').forEach((h) => h.classList.remove('sort-asc', 'sort-desc'));
    th.classList.add(asc ? 'sort-asc' : 'sort-desc');
    rows.sort((a, b) => {
      const at = a.cells[colIndex]?.textContent?.trim() ?? '';
      const bt = b.cells[colIndex]?.textContent?.trim() ?? '';
      const an = parseFloat(at.replace(/[\$,%]/g, ''));
      const bn = parseFloat(bt.replace(/[\$,%]/g, ''));
      if (!isNaN(an) && !isNaN(bn)) return asc ? an - bn : bn - an;
      return asc ? at.localeCompare(bt) : bt.localeCompare(at);
    });
    rows.forEach((r) => tbody.appendChild(r));

    const state = win.Table.initState(tableId);
    if (state.currentView !== 'table') {
      win.Table.renderChart(tableId, state.currentView);
    }
  };

  win.Table.applyAllFilters = (tableId: string) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const state = win.Table.states[tableId];
    if (!state) return;

    const searchQ = (state.searchQuery || '').toLowerCase().trim();
    const rows = [...table.querySelectorAll('tbody tr')] as HTMLTableRowElement[];
    let visible = 0;

    rows.forEach((row) => {
      const matchesSearch = !searchQ || row.textContent!.toLowerCase().includes(searchQ);
      
      let matchesColumnFilters = true;
      if (state.filters) {
        Object.entries(state.filters).forEach(([colIdxStr, filterVal]) => {
          if (filterVal) {
            const colIdx = parseInt(colIdxStr, 10);
            const cellVal = (row.cells[colIdx]?.textContent ?? '').trim();
            if (cellVal !== filterVal) {
              matchesColumnFilters = false;
            }
          }
        });
      }

      const isVisible = matchesSearch && matchesColumnFilters;
      (row as HTMLElement).classList.toggle('is-hidden', !isVisible);
      if (isVisible) visible++;
    });

    const countEl = document.getElementById(tableId + '-count');
    if (countEl) {
      countEl.textContent = visible < rows.length ? `${visible} / ${rows.length} rows` : `${rows.length} rows`;
    }

    if (state.currentView !== 'table') {
      win.Table.renderChart(tableId, state.currentView);
    }
  };

  win.Table.filter = (tableId: string, query: string) => {
    const state = win.Table.initState(tableId);
    state.searchQuery = query;
    win.Table.applyAllFilters(tableId);
  };

  win.Table.showFilterMenu = (tableId: string, colIndex: number, buttonEl: HTMLElement) => {
    const existing = document.querySelector('.mdn-filter-dropdown');
    if (existing) existing.remove();

    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const state = win.Table.initState(tableId);

    const rows = [...table.querySelectorAll('tbody tr')] as HTMLTableRowElement[];
    const values = rows
      .map(row => (row.cells[colIndex]?.textContent ?? '').trim())
      .filter(Boolean);
    const uniqueValues = Array.from(new Set(values)).sort();

    const dropdown = document.createElement('div');
    dropdown.className = 'mdn-filter-dropdown';

    const header = document.createElement('div');
    header.className = 'mdn-filter-dropdown-header';
    header.textContent = 'Filter Column';
    dropdown.appendChild(header);

    const allItem = document.createElement('div');
    allItem.className = `mdn-filter-item${!state.filters[colIndex] ? ' is-active' : ''}`;
    allItem.textContent = '(All)';
    allItem.onclick = () => {
      state.filters[colIndex] = null;
      buttonEl.classList.remove('is-active');
      win.Table.applyAllFilters(tableId);
      dropdown.remove();
    };
    dropdown.appendChild(allItem);

    uniqueValues.forEach(val => {
      const isActive = state.filters[colIndex] === val;
      const item = document.createElement('div');
      item.className = `mdn-filter-item${isActive ? ' is-active' : ''}`;
      item.textContent = val;
      item.onclick = () => {
        state.filters[colIndex] = val;
        buttonEl.classList.add('is-active');
        win.Table.applyAllFilters(tableId);
        dropdown.remove();
      };
      dropdown.appendChild(item);
    });

    document.body.appendChild(dropdown);
    const rect = buttonEl.getBoundingClientRect();
    dropdown.style.top = `${rect.bottom + window.scrollY + 4}px`;
    dropdown.style.left = `${rect.left + window.scrollX}px`;

    const outsideClickListener = (e: MouseEvent) => {
      if (!dropdown.contains(e.target as Node) && e.target !== buttonEl) {
        dropdown.remove();
        document.removeEventListener('click', outsideClickListener);
      }
    };
    setTimeout(() => {
      document.addEventListener('click', outsideClickListener);
    }, 0);
  };

  win.Table.toggleCollapse = (tableId: string) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const state = win.Table.initState(tableId);
    const rows = table.querySelectorAll('tbody tr');
    const btn = document.getElementById(tableId + '-toggle-btn');
    const collapsed = rows[15]?.classList.contains('is-collapsed-row');
    rows.forEach((row, idx) => {
      if (idx >= 15) (row as HTMLElement).classList.toggle('is-collapsed-row', !collapsed);
    });
    state.expanded = collapsed;
    if (btn) btn.textContent = collapsed ? 'Show Less' : 'Show More';
  };

  win.Table.updateCount = (tableId: string) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const total = table.querySelectorAll('tbody tr').length;
    const countEl = document.getElementById(tableId + '-count');
    if (countEl) countEl.textContent = `${total} rows`;
  };

  win.Table.detectChartable = (tableId: string) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const state = win.Table.initState(tableId);
    const headers = [...table.querySelectorAll('thead th')];
    const rows = [...table.querySelectorAll('tbody tr')] as HTMLTableRowElement[];

    // Find numeric columns and text label columns
    const numericCols: number[] = [];
    const labelCols: number[] = [];

    headers.forEach((_, idx) => {
      let isNumeric = true;
      let hasVal = false;
      rows.slice(0, 10).forEach(row => {
        const text = row.cells[idx]?.textContent?.trim() ?? '';
        if (!text) return;
        const clean = text.replace(/[\$,%]/g, '');
        if (isNaN(Number(clean))) {
          isNumeric = false;
        } else {
          hasVal = true;
        }
      });
      if (isNumeric && hasVal) {
        numericCols.push(idx);
      } else {
        labelCols.push(idx);
      }
    });

    if (numericCols.length > 0) {
      const labelColIdx = labelCols.length > 0 ? labelCols[0] : 0;
      const dataColIdxs = numericCols.filter(idx => idx !== labelColIdx);

      if (dataColIdxs.length > 0) {
        state.chartable = true;
        state.labelColIdx = labelColIdx;
        state.dataColIdxs = dataColIdxs;

        const switcher = document.getElementById(tableId + '-switcher');
        if (switcher && !switcher.innerHTML.trim()) {
          switcher.innerHTML = `
            <button id="${tableId}-view-table" class="is-active" onclick="Table.switchView('${tableId}', 'table')" title="View Table">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/></svg> Table
            </button>
            <button id="${tableId}-view-bar" onclick="Table.switchView('${tableId}', 'bar')" title="Bar Chart">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg> Bar
            </button>
            <button id="${tableId}-view-line" onclick="Table.switchView('${tableId}', 'line')" title="Line Chart">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M3 3v18h18"/><path d="m18.7 8-5.1 5.2-2.8-2.7L7 14.3"/></svg> Line
            </button>
            <button id="${tableId}-view-pie" onclick="Table.switchView('${tableId}', 'pie')" title="Pie Chart">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"/><path d="M22 12A10 10 0 0 0 12 2v10z"/></svg> Pie
            </button>
          `;
        }
      }
    }
  };

  win.Table.switchView = (tableId: string, view: string) => {
    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;
    const state = win.Table.initState(tableId);
    state.currentView = view;

    const switcher = document.getElementById(tableId + '-switcher');
    if (switcher) {
      switcher.querySelectorAll('button').forEach(btn => {
        btn.classList.toggle('is-active', btn.id === `${tableId}-view-${view}`);
      });
    }

    const scrollEl = document.getElementById(tableId + '-scroll');
    const chartContainer = document.getElementById(tableId + '-chart-container');
    const toggleBtn = document.getElementById(tableId + '-toggle-btn');

    if (view === 'table') {
      if (scrollEl) scrollEl.style.display = '';
      if (toggleBtn && state.expanded !== undefined) {
        const rows = table.querySelectorAll('tbody tr').length;
        if (rows > 15 && !state.searchQuery) {
          toggleBtn.style.display = '';
        }
      }
      if (chartContainer) chartContainer.style.display = 'none';
    } else {
      if (scrollEl) scrollEl.style.display = 'none';
      if (toggleBtn) toggleBtn.style.display = 'none';
      if (chartContainer) chartContainer.style.display = 'block';
      win.Table.renderChart(tableId, view);
    }
  };

  win.Table.getChartColors = (count: number, isDark: boolean) => {
    const baseColors = isDark 
      ? ['#8b7cf8', '#34d399', '#f87171', '#60a5fa', '#fbbf24', '#ec4899', '#a855f7', '#14b8a6']
      : ['#6d5ef0', '#10b981', '#ef4444', '#3b82f6', '#f59e0b', '#db2777', '#8b5cf6', '#0d9488'];
    const result = [];
    for (let i = 0; i < count; i++) {
      result.push(baseColors[i % baseColors.length]);
    }
    return result;
  };

  win.Table.renderChart = (tableId: string, viewType: string) => {
    const state = win.Table.initState(tableId);
    if (!state.chartable) return;

    const canvas = document.getElementById(tableId + '-chart-canvas') as HTMLCanvasElement | null;
    if (!canvas) return;

    if (state.chartInstance) {
      state.chartInstance.destroy();
      state.chartInstance = null;
    }

    const table = document.getElementById(tableId) as HTMLTableElement | null;
    if (!table) return;

    const rows = ([...table.querySelectorAll('tbody tr')] as HTMLTableRowElement[]).filter(
      row => !row.classList.contains('is-hidden')
    );

    if (rows.length === 0) {
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.font = '13px sans-serif';
        ctx.fillStyle = 'var(--txm)';
        ctx.textAlign = 'center';
        ctx.fillText('No data to display in chart', canvas.width / 2, canvas.height / 2);
      }
      return;
    }

    const MAX_CHART_ROWS = 50;
    const chartRows = rows.slice(0, MAX_CHART_ROWS);

    const labels = chartRows.map(row => {
      const text = row.cells[state.labelColIdx]?.textContent?.trim() ?? '';
      return text.length > 25 ? text.slice(0, 22) + '...' : text;
    });

    const isDark = document.documentElement.dataset.theme === 'dark' || 
      (document.documentElement.dataset.theme === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches);
    const styles = getComputedStyle(document.documentElement);
    const colors = win.Table.getChartColors(state.dataColIdxs.length, isDark);

    const datasets = state.dataColIdxs.map((colIdx: number, dsIdx: number) => {
      const headerText = table.querySelectorAll('thead th')[colIdx]?.querySelector('.mdn-th-text')?.textContent?.trim() ?? `Series ${dsIdx + 1}`;
      const data = chartRows.map(row => {
        const text = row.cells[colIdx]?.textContent?.trim() ?? '0';
        const clean = text.replace(/[\$,%]/g, '').trim();
        return parseFloat(clean) || 0;
      });

      const color = colors[dsIdx];

      if (viewType === 'pie') {
        const pieColors = win.Table.getChartColors(data.length, isDark);
        return {
          label: headerText,
          data: data,
          backgroundColor: pieColors.map((c: string) => c + 'cc'),
          borderColor: pieColors,
          borderWidth: 1
        };
      }

      return {
        label: headerText,
        data: data,
        backgroundColor: color + '33',
        borderColor: color,
        borderWidth: 2,
        tension: 0.1
      };
    });

    const finalDatasets = viewType === 'pie' ? [datasets[0]] : datasets;

    if (typeof win.Chart !== 'undefined') {
      state.chartInstance = new win.Chart(canvas, {
        type: viewType === 'pie' ? 'doughnut' : viewType,
        data: {
          labels: labels,
          datasets: finalDatasets
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              display: true,
              position: 'bottom',
              labels: {
                color: styles.getPropertyValue('--tx2').trim() || '#9191a4',
                font: { family: 'var(--font-ui)' }
              }
            }
          },
          scales: viewType === 'pie' ? undefined : {
            x: {
              grid: { color: styles.getPropertyValue('--bd').trim() || 'rgba(255,255,255,0.07)' },
              ticks: { color: styles.getPropertyValue('--tx2').trim() || '#9191a4', font: { family: 'var(--font-ui)' } }
            },
            y: {
              grid: { color: styles.getPropertyValue('--bd').trim() || 'rgba(255,255,255,0.07)' },
              ticks: { color: styles.getPropertyValue('--tx2').trim() || '#9191a4', font: { family: 'var(--font-ui)' } }
            }
          }
        }
      });
    }
  };

  // Sidebar.toggleFolder (for inline handlers)
  if (!win.Sidebar) win.Sidebar = {};
  win.Sidebar.toggleFolder = (el: HTMLElement) => {
    const folder = el.closest('.tree-folder') as HTMLElement | null;
    if (!folder) return;
    folder.classList.toggle('is-open');
    const children = folder.querySelector('.tree-folder__children') as HTMLElement | null;
    if (children) children.classList.toggle('is-hidden', !folder.classList.contains('is-open'));
  };

  // Nav.go (for inline handlers)
  if (!win.Nav) win.Nav = {};
  win.Nav.go = (_fsPath: string | null) => {
    // Handled by React navigate - but provide fallback for rendered HTML links
  };
}
