export const ACTIONS_LIST = [
  { id: 'findCurrentFile', label: 'Find in current file', scope: 'both' },
  { id: 'searchCurrent', label: 'Search current workspace', scope: 'desktop' },
  { id: 'searchAllTabs', label: 'Search all tabs', scope: 'desktop' },
  { id: 'back', label: 'Back to previous file', scope: 'both' },
  { id: 'forward', label: 'Go to next file', scope: 'both' },
  { id: 'welcome', label: 'Go to welcome page', scope: 'both' },
  { id: 'settings', label: 'Toggle settings modal', scope: 'both' },
  { id: 'toggleTheme', label: 'Toggle light/dark mode', scope: 'both' },
  { id: 'toggleHtmlPreview', label: 'Toggle default HTML preview', scope: 'both' },
  { id: 'refresh', label: 'Refresh current file', scope: 'desktop' },
  { id: 'collapseAll', label: 'Collapse all headings', scope: 'desktop' },
  { id: 'expandAll', label: 'Expand all headings', scope: 'desktop' },
  { id: 'workspaceSelection', label: 'Go to workspace selection', scope: 'both' },
  { id: 'toggleSidebar', label: 'Toggle sidebar visibility', scope: 'desktop' },
  { id: 'toggleDesktopViewMode', label: 'Toggle Tabs/Focus view', scope: 'electron' },
  { id: 'openCurrentDocumentLocation', label: 'Open current document folder', scope: 'electron' },
  { id: 'closeContentTab', label: 'Close current document tab', scope: 'electron' },
  { id: 'closeAllContentTabs', label: 'Close all document tabs', scope: 'electron' },
  { id: 'closeContentTabsToRight', label: 'Close document tabs to the right', scope: 'electron' },
  { id: 'closeOtherContentTabs', label: 'Close other document tabs', scope: 'electron' },
  { id: 'toggleToc', label: 'Toggle table of contents panel', scope: 'both' },
  { id: 'toggleFocusMode', label: 'Toggle focus mode', scope: 'both' },
  { id: 'sidebarCursorMode', label: 'Sidebar cursor mode', scope: 'both' },
  { id: 'locateFile', label: 'Locate current open file in sidebar', scope: 'both' },
  { id: 'zoomIn', label: 'Zoom in', scope: 'desktop' },
  { id: 'zoomOut', label: 'Zoom out', scope: 'desktop' },
];
