import { PET_THEME_STYLE_OPTIONS, THEME_STYLE_OPTIONS } from '../../contexts/appStateConstants';
import { CUSTOM_THEME_COLOR_OPTIONS } from '../../theme/customThemes';
import type { CustomTheme, CustomThemeColorOverrides, CustomThemeScheme, ThemeMode, ThemeStyle } from '../../types';

export const DEFAULT_DARK_COLORS: CustomThemeColorOverrides = { bg: '#151518', surface: '#1d1d22', elevated: '#25252c', hover: '#2d2d36', active: '#363641', code: '#111114', text: '#f4efe8', textMuted: '#a59e95', textSoft: '#5a544e', textSubtle: '#7c756c', accent: '#ff9130', accentText: '#ffb875', border: '#3d352f', borderStrong: '#55483d', success: '#34d399', danger: '#f87171', chart1: '#ff9130', chart2: '#34d399', chart3: '#f87171', chart4: '#60a5fa' };
export const DEFAULT_LIGHT_COLORS: CustomThemeColorOverrides = { bg: '#fdfbf7', surface: '#ffffff', elevated: '#f5f2eb', hover: '#eae5da', active: '#ded7c9', code: '#f6f3eb', text: '#1f1a14', textMuted: '#5c5246', textSoft: '#5a4f44', textSubtle: '#8a7c6e', accent: '#ea580c', accentText: '#ea580c', border: '#d7c8b8', borderStrong: '#bba994', success: '#10b981', danger: '#ef4444', chart1: '#ea580c', chart2: '#10b981', chart3: '#ef4444', chart4: '#3b82f6' };
export const BASE_STYLE_OPTIONS = [...THEME_STYLE_OPTIONS.map((option) => ({ id: option.id, label: option.label })), ...PET_THEME_STYLE_OPTIONS.map((option) => ({ id: option.id, label: `Pet - ${option.label}` }))] as const;
export const DENSITY_OPTIONS = [{ value: 'compact', label: 'Compact' }, { value: 'comfortable', label: 'Comfortable' }, { value: 'spacious', label: 'Spacious' }] as const;
export const IMAGE_FIT_OPTIONS = [{ value: 'cover', label: 'Cover' }, { value: 'contain', label: 'Contain' }] as const;
export const REMIX_STATUS_TIMEOUT_MS = 5000;

export function makeThemeId() { return `theme-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
export function normalizeHex(value: string | undefined, fallback: string) { if (!value) return fallback; const trimmed = value.trim(); return /^#[0-9a-f]{6}$/i.test(trimmed) ? trimmed.toLowerCase() : fallback; }
function colorToHex(value: string, fallback: string) { const trimmed = value.trim(); if (/^#[0-9a-f]{6}$/i.test(trimmed)) return trimmed.toLowerCase(); const match = trimmed.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)/i); if (!match) return fallback; const [, r, g, b] = match; return [r, g, b].map((part) => Math.max(0, Math.min(255, Number(part))).toString(16).padStart(2, '0')).join('').replace(/^/, '#'); }
function readCurrentColors(scheme: CustomThemeScheme): CustomThemeColorOverrides { const styles = window.getComputedStyle(document.documentElement); const fallback = scheme === 'light' ? DEFAULT_LIGHT_COLORS : DEFAULT_DARK_COLORS; return Object.fromEntries(CUSTOM_THEME_COLOR_OPTIONS.map((option) => [option.key, colorToHex(styles.getPropertyValue(option.cssVar), fallback[option.key] ?? '#ffffff')])); }
export function createThemeFromCurrent(name = 'New remix'): CustomTheme { const now = Date.now(); return { id: makeThemeId(), name, baseStyle: (document.documentElement.dataset.themeStyle as ThemeStyle | undefined) ?? 'default', colorMode: (document.documentElement.dataset.theme as ThemeMode | undefined) ?? 'auto', createdAt: now, updatedAt: now, colors: { dark: readCurrentColors('dark'), light: readCurrentColors('light') }, layout: { density: 'comfortable', radius: 8, strokeWidth: 1, contentPadding: 36, sectionGap: 14 }, background: { type: 'none', opacity: 0.16, fit: 'cover', position: 'center', blur: 0 } }; }
export function updateTheme(themes: readonly CustomTheme[], id: string, updater: (theme: CustomTheme) => CustomTheme) { return themes.map((theme) => theme.id === id ? { ...updater(theme), updatedAt: Date.now() } : theme); }
export function formatRangeValue(value: number, unit: 'px' | '%') { return unit === '%' ? `${Math.round(value * 100)}%` : `${value}${unit}`; }
export function getBackgroundImageLimitMessage(fileSize: number) { return `Image is too large. Use a smaller image under 620 KB. Selected: ${Math.round(fileSize / 1024)} KB.`; }
