export const productionGlobs = [
  'electron/**/*.js',
  'vscode/src/**/*.ts',
  'vscode/scripts/**/*.js',
  'ui/src/**/*.{ts,tsx,js}',
  'ui/vite.config.ts',
  'chromium-xtension/src/**/*.{ts,tsx}',
  'chromium-xtension/popup.js',
  'chromium-xtension/vite.config.ts',
];

export const productionIgnore = [
  '**/*.d.ts',
  '**/vite-env.d.ts',
  'ui/src/types.ts',
  'ui/src/desktop/types.ts',
  'ui/src/markdown/types.ts',
  'ui/src/platform/bridge.ts',
  'vscode/src/types.ts',
  '**/node_modules/**',
  '**/dist/**',
  '**/out/**',
  'vscode/ui/**',
  'electron/ui/**',
  'electron/vscode/**',
];

export const coverageManifest: Record<string, string[]> = {
  'electron/window/debug-tools.js': ['tests/unit/electron/debug-tools.test.ts'],
  'electron/render/document-converter.js': ['tests/unit/electron/document-converter.test.ts'],
  'electron/core/ipc-handlers.js': ['tests/unit/electron/ipc-handlers.test.ts'],
  'electron/main.js': ['tests/unit/electron/main-runtime.test.ts'],
  'electron/core/main-bootstrap.js': ['tests/unit/electron/main-runtime.test.ts'],
  'electron/core/main-runtime.js': ['tests/unit/electron/main-runtime.test.ts'],
  'electron/render/markdown-renderer.js': ['tests/unit/electron/markdown-renderer.test.ts'],
  'electron/perf/perf-timer.js': ['tests/unit/electron/perf-timer.test.ts'],
  'electron/preload/preload.js': ['tests/unit/electron/preload-api.test.ts'],
  'electron/preload/preload-api.js': ['tests/unit/electron/preload-api.test.ts'],
  'electron/workspace/recents.js': ['tests/unit/electron/recents.test.ts'],
  'electron/workspace/scanner.js': ['tests/unit/electron/scanner.test.ts'],
  'electron/search/search-index.js': ['tests/unit/electron/search-index.test.ts'],
  'electron/search/search-worker-controller.js': ['tests/unit/electron/search-worker-controller.test.ts'],
  'electron/search/search-worker.js': ['tests/unit/electron/search-worker.test.ts'],
  'electron/core/startup-workspace.js': ['tests/unit/electron/startup-workspace.test.ts'],
  'electron/window/tray.js': ['tests/unit/electron/tray.test.ts'],
  'electron/search/unicode-search.js': ['tests/unit/electron/unicode-search.test.ts'],
  'electron/update/update-helper.js': ['tests/unit/electron/update-helper.test.ts'],
  'electron/update/update-manager.js': ['tests/unit/electron/update-manager.test.ts'],
  'electron/window/window.js': ['tests/unit/electron/window.test.ts'],
  'electron/workspace/workspace-refresh.js': ['tests/unit/electron/workspace-refresh.test.ts'],
  'electron/workspace/workspace-watch.js': ['tests/unit/electron/workspace-watch.test.ts'],
  'electron/youtube/youtube-headers.js': ['tests/unit/electron/youtube-headers.test.ts'],

  'vscode/scripts/bundle-markdown-them.js': ['tests/unit/build/copy-ui.test.ts'],
  'vscode/scripts/copy-ui.js': ['tests/unit/build/copy-ui.test.ts'],
  'vscode/src/core/documentConversion.ts': ['tests/unit/vscode/documentConversion.test.ts'],
  'vscode/src/core/panel.ts': ['tests/unit/vscode/panel.test.ts'],
  'vscode/src/core/scanner.ts': ['tests/unit/vscode/scanner.test.ts'],
  'vscode/src/core/unicodeSearch.ts': ['tests/unit/vscode/unicodeSearch.test.ts'],
  'vscode/src/extension.ts': ['tests/unit/vscode/extension.test.ts'],
  'vscode/src/markdown/codeRenderer.ts': ['tests/unit/vscode/codeRenderer.test.ts'],
  'vscode/src/markdown/highlighter.ts': ['tests/unit/vscode/highlighter.test.ts'],
  'vscode/src/markdown/inline.ts': ['tests/unit/vscode/inline.test.ts'],
  'vscode/src/markdown/parser.ts': ['tests/unit/vscode/parser.test.ts'],
  'vscode/src/markdown/renderer.ts': ['tests/unit/vscode/renderer.test.ts'],
  'vscode/src/utils.ts': ['tests/unit/vscode/utils.test.ts'],

  'ui/src/App.tsx': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/AppShell.tsx': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/main.tsx': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/contexts/appStateReducer.ts': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/components/Content/Content.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/ContentTabs.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/InteractiveComponents.ts': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/WelcomePage.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Desktop/DesktopTabBar.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Desktop/FloatingTabToolbar.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Modal/MediaModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/SwitchWorkspaceModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/TermsModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/ThemeOnboardingModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Search/FindInFilePanel.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Search/SearchOverlay.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Settings/SettingsModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Settings/ThemeRemixModal.tsx': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/components/Settings/ThemeStylePicker.tsx': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/components/Sidebar/Sidebar.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Sidebar/SidebarSearch.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Sidebar/TreeNode.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/TOC/TableOfContents.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Topbar/Topbar.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Workspace/RecentWorkspaceItem.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/RecentWorkspacesModal.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/WorkspaceSelection.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/WorkspaceWindowControls.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/workspaceSelectionUtils.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/shared/InteractiveBackground.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/TabContextMenu.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/ToolbarActionMenu.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/TooltipButton.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/icons.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/contexts/AppStateContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/NavigationContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/PlatformContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/appStateConstants.ts': ['tests/unit/ui/contexts/state-utils.test.ts'],
  'ui/src/contexts/scope-focus-reconcile.js': ['tests/unit/ui/contexts/state-utils.test.ts'],
  'ui/src/contexts/translations.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/contexts/translationsData.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/contexts/welcomeTranslations.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/desktop/constants.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/desktop/desktopTabs.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/dom/codeLineHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/copyHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/globalHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/tableHandlers.ts': ['tests/unit/ui/dom/tableHandlers.test.ts'],
  'ui/src/hooks/useDesktopTabs.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/hooks/useFileDropOpen.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/hooks/useKeyboard.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useResize.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useScrollVisibility.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useUpdateCheck.ts': ['tests/unit/ui/hooks/useUpdateCheck.test.ts', 'tests/unit/ui/hooks/useUpdateCheck-hook.test.ts'],
  'ui/src/hooks/usePlatform.ts': ['tests/unit/ui/hooks/usePlatform.test.ts'],
  'ui/src/hooks/useIsDark.ts': ['tests/unit/ui/hooks/useIsDark.test.ts'],
  'ui/src/lib/petImages.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/lib/renderLibs.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/markdown/codeRenderer.ts': ['tests/unit/ui/markdown/codeRenderer.test.ts'],
  'ui/src/markdown/highlighter.ts': ['tests/unit/ui/markdown/highlighter.test.ts'],
  'ui/src/markdown/inline.ts': ['tests/unit/ui/markdown/inline.test.ts'],
  'ui/src/markdown/parser.ts': ['tests/unit/ui/markdown/parser.test.ts'],
  'ui/src/markdown/renderer.ts': ['tests/unit/ui/markdown/renderer.test.ts'],
  'ui/src/markdown/utils.ts': ['tests/unit/ui/markdown/utils.test.ts'],
  'ui/src/markdown/mediaUrls.ts': ['tests/unit/ui/markdown/mediaUrls.test.ts'],
  'ui/src/platform/chrome.ts': ['tests/unit/ui/platform-bridges.test.ts', 'tests/unit/chromium/chrome-bridge.test.ts'],
  'ui/src/platform/electron.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/platform/vscode.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/platform/web.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/settings/settingsImportExport.ts': ['tests/unit/ui/settings-import-export.test.ts'],
  'ui/src/theme/customThemes.ts': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/utils/searchJump.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/shortcuts.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/toolbar-menu.js': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/unicodeSearch.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/vite.config.ts': ['tests/unit/build/copy-ui.test.ts'],

  'chromium-xtension/src/chrome-host.ts': ['tests/unit/chromium/chrome-host.test.ts'],
  'chromium-xtension/src/file-access.ts': ['tests/unit/chromium/file-access.test.ts'],
  'chromium-xtension/src/main-chrome.tsx': ['tests/unit/chromium/chrome-host.test.ts'],
  'chromium-xtension/src/markdown-renderer.ts': ['tests/unit/chromium/markdown-renderer.test.ts'],
  'chromium-xtension/src/media-resolver.ts': ['tests/unit/chromium/media-resolver.test.ts'],
  'chromium-xtension/src/recent-workspaces.ts': ['tests/unit/chromium/file-access.test.ts'],
  'chromium-xtension/src/scanner.ts': ['tests/unit/chromium/scanner.test.ts'],
  'chromium-xtension/src/search-index.ts': ['tests/unit/chromium/search-index.test.ts'],
  'chromium-xtension/popup.js': ['tests/unit/chromium/chrome-host.test.ts'],
  'chromium-xtension/vite.config.ts': ['tests/unit/build/copy-ui.test.ts'],
};
