export const productionGlobs = [
  'desktop/**/*.js',
  'vscode/src/**/*.ts',
  'vscode/scripts/**/*.js',
  'ui/src/**/*.{ts,tsx,js}',
  'ui/vite.config.ts',
  'chromium-xtension/src/**/*.{ts,tsx}',
  'chromium-xtension/popup.js',
  'chromium-xtension/vite.config.ts',
];

export const productionIgnore = [
  '**/*.d.ts',
  '**/vite-env.d.ts',
  'ui/src/types.ts',
  'ui/src/desktop/types.ts',
  'ui/src/markdown/types.ts',
  'ui/src/platform/bridge.ts',
  'vscode/src/types.ts',
  '**/node_modules/**',
  '**/dist/**',
  '**/out/**',
  'vscode/ui/**',
  'desktop/ui/**',
  'desktop/vscode/**',
];

export const coverageManifest: Record<string, string[]> = {
  'desktop/debug-tools.js': ['tests/unit/desktop/debug-tools.test.ts'],
  'desktop/document-converter.js': ['tests/unit/desktop/document-converter.test.ts'],
  'desktop/ipc-handlers.js': ['tests/unit/desktop/ipc-handlers.test.ts'],
  'desktop/main.js': ['tests/unit/desktop/main-runtime.test.ts'],
  'desktop/main-bootstrap.js': ['tests/unit/desktop/main-runtime.test.ts'],
  'desktop/main-runtime.js': ['tests/unit/desktop/main-runtime.test.ts'],
  'desktop/markdown-renderer.js': ['tests/unit/desktop/markdown-renderer.test.ts'],
  'desktop/perf-timer.js': ['tests/unit/desktop/perf-timer.test.ts'],
  'desktop/preload.js': ['tests/unit/desktop/preload-api.test.ts'],
  'desktop/preload-api.js': ['tests/unit/desktop/preload-api.test.ts'],
  'desktop/recents.js': ['tests/unit/desktop/recents.test.ts'],
  'desktop/scanner.js': ['tests/unit/desktop/scanner.test.ts'],
  'desktop/search-index.js': ['tests/unit/desktop/search-index.test.ts'],
  'desktop/search-worker-controller.js': ['tests/unit/desktop/search-worker-controller.test.ts'],
  'desktop/search-worker.js': ['tests/unit/desktop/search-worker.test.ts'],
  'desktop/startup-workspace.js': ['tests/unit/desktop/startup-workspace.test.ts'],
  'desktop/tray.js': ['tests/unit/desktop/tray.test.ts'],
  'desktop/unicode-search.js': ['tests/unit/desktop/unicode-search.test.ts'],
  'desktop/update-helper.js': ['tests/unit/desktop/update-helper.test.ts'],
  'desktop/update-manager.js': ['tests/unit/desktop/update-manager.test.ts'],
  'desktop/window.js': ['tests/unit/desktop/window.test.ts'],
  'desktop/workspace-refresh.js': ['tests/unit/desktop/workspace-refresh.test.ts'],
  'desktop/workspace-watch.js': ['tests/unit/desktop/workspace-watch.test.ts'],
  'desktop/youtube-headers.js': ['tests/unit/desktop/youtube-headers.test.ts'],

  'vscode/scripts/bundle-markdown-them.js': ['tests/unit/build/copy-ui.test.ts'],
  'vscode/scripts/copy-ui.js': ['tests/unit/build/copy-ui.test.ts'],
  'vscode/src/core/documentConversion.ts': ['tests/unit/vscode/documentConversion.test.ts'],
  'vscode/src/core/panel.ts': ['tests/unit/vscode/panel.test.ts'],
  'vscode/src/core/scanner.ts': ['tests/unit/vscode/scanner.test.ts'],
  'vscode/src/core/unicodeSearch.ts': ['tests/unit/vscode/unicodeSearch.test.ts'],
  'vscode/src/extension.ts': ['tests/unit/vscode/extension.test.ts'],
  'vscode/src/markdown/codeRenderer.ts': ['tests/unit/vscode/codeRenderer.test.ts'],
  'vscode/src/markdown/highlighter.ts': ['tests/unit/vscode/highlighter.test.ts'],
  'vscode/src/markdown/inline.ts': ['tests/unit/vscode/inline.test.ts'],
  'vscode/src/markdown/parser.ts': ['tests/unit/vscode/parser.test.ts'],
  'vscode/src/markdown/renderer.ts': ['tests/unit/vscode/renderer.test.ts'],
  'vscode/src/utils.ts': ['tests/unit/vscode/utils.test.ts'],

  'ui/src/App.tsx': ['tests/unit/ui/main.test.ts'],
  'ui/src/AppShell.tsx': ['tests/unit/ui/main.test.ts'],
  'ui/src/main.tsx': ['tests/unit/ui/main.test.ts'],
  'ui/src/contexts/appStateReducer.ts': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/components/Content/Content.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/ContentTabs.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/InteractiveComponents.ts': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Content/WelcomePage.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Desktop/DesktopTabBar.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Desktop/FloatingTabToolbar.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Modal/MediaModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/SwitchWorkspaceModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/TermsModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Modal/ThemeOnboardingModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Search/FindInFilePanel.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Search/SearchOverlay.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Settings/SettingsModal.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Settings/ThemeRemixModal.tsx': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/components/Settings/ThemeStylePicker.tsx': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/components/Sidebar/Sidebar.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Sidebar/SidebarSearch.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Sidebar/TreeNode.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/TOC/TableOfContents.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Topbar/Topbar.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/Workspace/RecentWorkspaceItem.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/RecentWorkspacesModal.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/WorkspaceSelection.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/WorkspaceWindowControls.tsx': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/Workspace/workspaceSelectionUtils.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/components/shared/InteractiveBackground.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/TabContextMenu.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/ToolbarActionMenu.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/TooltipButton.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/components/shared/icons.tsx': ['tests/unit/ui/components/content.test.tsx'],
  'ui/src/contexts/AppStateContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/NavigationContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/PlatformContext.tsx': ['tests/unit/ui/contexts/app-state.test.ts'],
  'ui/src/contexts/appStateConstants.ts': ['tests/unit/ui/contexts/state-utils.test.ts'],
  'ui/src/contexts/scope-focus-reconcile.js': ['tests/unit/ui/contexts/state-utils.test.ts'],
  'ui/src/contexts/translations.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/contexts/translationsData.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/contexts/welcomeTranslations.ts': ['tests/unit/ui/contexts/translations.test.ts'],
  'ui/src/desktop/constants.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/desktop/desktopTabs.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/dom/codeLineHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/copyHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/globalHandlers.ts': ['tests/unit/ui/dom/copyHandlers.test.ts'],
  'ui/src/dom/tableHandlers.ts': ['tests/unit/ui/dom/tableHandlers.test.ts'],
  'ui/src/hooks/useDesktopTabs.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/hooks/useFileDropOpen.ts': ['tests/unit/ui/desktop-tabs.test.ts'],
  'ui/src/hooks/useKeyboard.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useResize.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useScrollVisibility.ts': ['tests/unit/ui/hooks/useKeyboard.test.ts'],
  'ui/src/hooks/useUpdateCheck.ts': ['tests/unit/ui/hooks/useUpdateCheck.test.ts'],
  'ui/src/lib/petImages.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/lib/renderLibs.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/markdown/codeRenderer.ts': ['tests/unit/ui/markdown/codeRenderer.test.ts'],
  'ui/src/markdown/highlighter.ts': ['tests/unit/ui/markdown/highlighter.test.ts'],
  'ui/src/markdown/inline.ts': ['tests/unit/ui/markdown/inline.test.ts'],
  'ui/src/markdown/parser.ts': ['tests/unit/ui/markdown/parser.test.ts'],
  'ui/src/markdown/renderer.ts': ['tests/unit/ui/markdown/renderer.test.ts'],
  'ui/src/markdown/utils.ts': ['tests/unit/ui/markdown/utils.test.ts'],
  'ui/src/markdown/mediaUrls.ts': ['tests/unit/ui/markdown/mediaUrls.test.ts'],
  'ui/src/platform/chrome.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/platform/electron.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/platform/vscode.ts': ['tests/unit/ui/platform-bridges.test.ts'],
  'ui/src/settings/settingsImportExport.ts': ['tests/unit/ui/settings-import-export.test.ts'],
  'ui/src/theme/customThemes.ts': ['tests/unit/ui/custom-themes.test.ts'],
  'ui/src/utils/searchJump.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/shortcuts.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/toolbar-menu.js': ['tests/unit/ui/utils.test.ts'],
  'ui/src/utils/unicodeSearch.ts': ['tests/unit/ui/utils.test.ts'],
  'ui/vite.config.ts': ['tests/unit/build/copy-ui.test.ts'],

  'chromium-xtension/src/chrome-host.ts': ['tests/unit/desktop/scanner.test.ts'],
  'chromium-xtension/src/file-access.ts': ['tests/unit/desktop/scanner.test.ts'],
  'chromium-xtension/src/main-chrome.tsx': ['tests/unit/desktop/main-runtime.test.ts'],
  'chromium-xtension/src/markdown-renderer.ts': ['tests/unit/desktop/markdown-renderer.test.ts'],
  'chromium-xtension/src/media-resolver.ts': ['tests/unit/desktop/document-converter.test.ts'],
  'chromium-xtension/src/recent-workspaces.ts': ['tests/unit/desktop/recents.test.ts'],
  'chromium-xtension/src/scanner.ts': ['tests/unit/desktop/scanner.test.ts'],
  'chromium-xtension/src/search-index.ts': ['tests/unit/desktop/search-index.test.ts'],
  'chromium-xtension/popup.js': ['tests/unit/desktop/main.test.ts'],
  'chromium-xtension/vite.config.ts': ['tests/unit/build/copy-ui.test.ts'],
};
