export const exportScopeCoverageManifest: Record<string, string[]> = {
  'chromium-xtension/src/chrome-host-export.ts': ['tests/unit/chromium/chrome-host-export.test.ts'],
  'electron/core/pdf-export.js': ['tests/unit/electron/pdf-export.test.ts'],
  'electron/core/runtime-export-resources.js': ['tests/unit/electron/export-resources.test.ts'],
  'ui/src/components/Export/ExportCenterModal.tsx': [
    'tests/unit/ui/components/export-center-modal.test.tsx',
    'tests/unit/ui/components/export-center-close.test.tsx',
  ],
  'ui/src/components/Export/ExportCenterSourcePanel.tsx': ['tests/unit/ui/components/export-center-modal.test.tsx'],
  'ui/src/components/Export/exportSelectionModel.ts': ['tests/unit/ui/export/export-selection-model.test.ts'],
  'ui/src/components/Modal/ScopeViewModal.tsx': ['tests/unit/ui/components/scope-view-modal.test.tsx'],
  'ui/src/components/Modal/scopeHistory.ts': ['tests/unit/ui/components/scope-history.test.ts'],
  'ui/src/export/documentSnapshot.ts': ['tests/unit/ui/export/document-snapshot.test.ts'],
  'ui/src/export/exportHtml.ts': ['tests/unit/ui/export/export-html.test.ts'],
  'ui/src/export/exportModel.ts': ['tests/unit/ui/export/export-model.test.ts'],
  'ui/src/export/exportResources.ts': ['tests/unit/ui/export/export-resources.test.ts'],
  'ui/src/export/pdfExport.ts': ['tests/unit/ui/export/pdf-export-host.test.ts'],
  'ui/src/export/zipStore.ts': ['tests/unit/ui/export/zip-store.test.ts'],
  'vscode/src/core/panelExportResources.ts': ['tests/unit/vscode/panel-export-resources.test.ts'],
};
