export const exportScopeCoverageManifest: Record<string, string[]> = {
  'chromium-xtension/src/chrome-host-export.ts': ['tests/unit/chromium/chrome-host-export.test.ts'],
  'electron/core/pdf-export.js': ['tests/unit/electron/pdf-export.test.ts'],
  'electron/core/runtime-export-resources.js': ['tests/unit/electron/export-resources.test.ts'],
  'electron/core/runtime-export-save.js': ['tests/unit/electron/export-save.test.ts'],
  'ui/src/components/Export/ExportAdditionalFilesPanel.tsx': ['tests/unit/ui/components/export-source-controls.test.tsx'],
  'ui/src/components/Export/ExportCenterModal.tsx': ['tests/unit/ui/components/export-center-modal.test.tsx', 'tests/unit/ui/components/export-center-close.test.tsx'],
  'ui/src/components/Export/ExportCenterOptionsPanel.tsx': ['tests/unit/ui/components/export-center-modal.test.tsx', 'tests/unit/ui/components/export-center-close.test.tsx'],
  'ui/src/components/Export/ExportCenterSourcePanel.tsx': ['tests/unit/ui/components/export-source-controls.test.tsx'],
  'ui/src/components/Export/ExportMultiSelect.tsx': ['tests/unit/ui/components/export-source-controls.test.tsx'],
  'ui/src/components/Export/exportSelectionModel.ts': ['tests/unit/ui/export/export-selection-model.test.ts'],
  'ui/src/components/Modal/ScopeViewModal.tsx': ['tests/unit/ui/components/scope-view-modal.test.tsx'],
  'ui/src/components/Modal/scopeHistory.ts': ['tests/unit/ui/components/scope-history.test.ts'],
  'ui/src/components/shared/SearchableSelect.tsx': ['tests/unit/ui/components/export-source-controls.test.tsx'],
  'ui/src/dom/portableContentHandlers.ts': ['tests/unit/ui/dom/portable-runtime.test.ts'],
  'ui/src/dom/portableMediaViewer.ts': ['tests/unit/ui/dom/portable-runtime.test.ts'],
  'ui/src/export/documentSnapshot.ts': ['tests/unit/ui/export/document-snapshot.test.ts'],
  'ui/src/export/exportAssets.ts': ['tests/unit/ui/export/export-assets.test.ts'],
  'ui/src/export/exportHtml.ts': ['tests/unit/ui/export/export-html.test.ts'],
  'ui/src/export/exportModel.ts': ['tests/unit/ui/export/export-model.test.ts'],
  'ui/src/export/exportResources.ts': ['tests/unit/ui/export/export-resources.test.ts'],
  'ui/src/export/exportRuntimeAssets.ts': ['tests/unit/ui/export/export-runtime-assets.test.ts'],
  'ui/src/export/exportSave.ts': ['tests/unit/ui/export/export-save.test.ts'],
  'ui/src/export/exportSite.ts': ['tests/unit/ui/export/export-site.test.ts'],
  'ui/src/export/exportSnapshot.ts': ['tests/unit/ui/export/export-snapshot.test.ts'],
  'ui/src/export/exportTheme.ts': ['tests/unit/ui/export/export-theme.test.ts'],
  'ui/src/export/pdf/pdfComposer.ts': ['tests/unit/ui/export/pdf-composer.test.ts'],
  'ui/src/export/pdf/pdfFonts.ts': ['tests/unit/ui/export/pdf-composer.test.ts'],
  'ui/src/export/pdf/pdfSemantic.ts': ['tests/unit/ui/export/pdf-semantic.test.ts'],
  'ui/src/export/pdf/pdfVisualCapture.ts': ['tests/unit/ui/export/pdf-visual-capture.test.ts'],
  'ui/src/export/pdfExport.ts': ['tests/unit/ui/export/pdf-export-host.test.ts'],
  'ui/src/export/runtime/entry-charts.ts': ['tests/node/export-runtime-build.test.mjs'],
  'ui/src/export/runtime/entry-core.ts': ['tests/node/export-runtime-build.test.mjs'],
  'ui/src/export/runtime/entry-html-preview.ts': ['tests/node/export-runtime-build.test.mjs'],
  'ui/src/export/runtime/entry-media.ts': ['tests/node/export-runtime-build.test.mjs'],
  'ui/src/export/runtime/entry-table.ts': ['tests/node/export-runtime-build.test.mjs'],
  'ui/src/export/zipStore.ts': ['tests/unit/ui/export/zip-store.test.ts'],
  'vscode/src/core/panelExportResources.ts': ['tests/unit/vscode/panel-export-resources.test.ts'],
  'vscode/src/core/panelExportSave.ts': ['tests/unit/vscode/panel-export-save.test.ts'],
};
