export const workspaceInsightsCoverageManifest: Record<string, string[]> = {
  'chromium-xtension/src/chrome-host-insights.ts': ['tests/unit/chromium/chrome-host-insights.test.ts', 'tests/unit/chromium/chrome-host-insights-polling.test.ts'],
  'chromium-xtension/src/insights-host-router.ts': ['tests/unit/chromium/chrome-host-insights.test.ts'],
  'electron/core/runtime-insights-external.js': ['tests/unit/electron/insights-external.test.ts'],
  'electron/core/runtime-insights.js': ['tests/unit/electron/runtime-insights.test.ts'],
  'ui/src/components/Insights/DuplicatesView.tsx': ['tests/unit/ui/components/insights-lint-duplicates.test.tsx', 'tests/unit/ui/components/insights-settings-integration.test.tsx'],
  'ui/src/components/Insights/GalleryView.tsx': ['tests/unit/ui/components/insights-gallery-links.test.tsx', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/components/Insights/GraphView.tsx': ['tests/unit/ui/components/insights-graph-related-reports.test.tsx'],
  'ui/src/components/Insights/InsightsSettings.tsx': ['tests/unit/ui/components/workspace-insights-panel.test.tsx', 'tests/unit/ui/components/insights-settings-integration.test.tsx', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/components/Insights/LinksView.tsx': ['tests/unit/ui/components/insights-gallery-links.test.tsx', 'tests/unit/ui/components/insights-graph-related-reports.test.tsx', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/components/Insights/LintView.tsx': ['tests/unit/ui/components/insights-lint-duplicates.test.tsx', 'tests/unit/ui/components/insights-settings-integration.test.tsx', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/components/Insights/RelatedView.tsx': ['tests/unit/ui/components/insights-graph-related-reports.test.tsx', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/components/Insights/WorkspaceInsightsEntry.tsx': ['tests/unit/ui/components/workspace-insights-panel.test.tsx'],
  'ui/src/components/Insights/WorkspaceInsightsPanel.tsx': ['tests/unit/ui/components/workspace-insights-panel.test.tsx', 'tests/unit/ui/components/insights-settings-integration.test.tsx'],
  'ui/src/contexts/auditedUiTranslationsBase.ts': ['tests/contracts/translations-coverage.test.ts'],
  'ui/src/contexts/insightsTranslations.ts': ['tests/unit/ui/contexts/insights-translations.test.ts'],
  'ui/src/contexts/insightsUiTranslations.ts': ['tests/unit/ui/contexts/insights-translations.test.ts', 'tests/unit/ui/components/insights-localization.test.tsx'],
  'ui/src/insights/analyzeDocument.ts': ['tests/unit/ui/insights/analyze-document.test.ts'],
  'ui/src/insights/cache.ts': ['tests/unit/ui/insights/cache.test.ts'],
  'ui/src/insights/concurrency.ts': ['tests/unit/ui/insights/concurrency.test.ts'],
  'ui/src/insights/config.ts': ['tests/unit/ui/insights/contracts.test.ts', 'tests/unit/ui/insights/settings-store.test.ts'],
  'ui/src/insights/contracts.ts': ['tests/unit/ui/insights/contracts.test.ts'],
  'ui/src/insights/duplicates.ts': ['tests/unit/ui/insights/duplicates.test.ts'],
  'ui/src/insights/graph.ts': ['tests/unit/ui/insights/graph.test.ts'],
  'ui/src/insights/index.ts': ['tests/unit/ui/insights/index.test.ts'],
  'ui/src/insights/insights.worker.ts': ['tests/unit/ui/insights/worker-client.test.ts'],
  'ui/src/insights/lint.ts': ['tests/unit/ui/insights/lint.test.ts'],
  'ui/src/insights/patterns.ts': ['tests/unit/ui/insights/patterns.test.ts'],
  'ui/src/insights/relationships.ts': ['tests/unit/ui/insights/relationships.test.ts'],
  'ui/src/insights/reports.ts': ['tests/unit/ui/components/insights-graph-related-reports.test.tsx'],
  'ui/src/insights/settingsStore.ts': ['tests/unit/ui/insights/settings-store.test.ts'],
  'ui/src/insights/useWorkspaceInsights.ts': ['tests/unit/ui/insights/use-workspace-insights.test.tsx'],
  'ui/src/insights/workerClient.ts': ['tests/unit/ui/insights/worker-client.test.ts'],
  'ui/src/insights/workerProtocol.ts': ['tests/unit/ui/insights/worker-client.test.ts'],
  'ui/src/insights/workspaceIdentity.ts': ['tests/unit/ui/insights/workspace-identity.test.ts'],
  'ui/src/insights/workspaceInsightsSession.ts': ['tests/unit/ui/insights/use-workspace-insights.test.tsx'],
  'ui/src/markdown/anchors.ts': ['tests/unit/ui/markdown/anchors.test.ts'],
  'ui/src/markdown/frontmatter.ts': ['tests/unit/ui/markdown/frontmatter.test.ts'],
  'ui/src/markdown/references.ts': ['tests/unit/ui/markdown/references.test.ts'],
  'ui/src/markdown/transclusion.ts': ['tests/unit/ui/markdown/transclusion.test.ts'],
  'ui/src/markdown/wikiLinks.ts': ['tests/unit/ui/markdown/wiki-links.test.ts'],
  'ui/src/settings/settingsImportExportBase.ts': ['tests/unit/ui/settings-import-export.test.ts'],
  'vscode/src/core/panelInsights.ts': ['tests/unit/vscode/panel-insights.test.ts'],
  'vscode/src/core/panelInsightsExternal.ts': ['tests/unit/vscode/insights-external.test.ts'],
};
